<?php
namespace App\Controllers;

use App\Models\CliModel;
use App\Models\UserModel;
use CodeIgniter\Controller;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Psr\Log\LoggerInterface;

class Cli extends Controller
{

    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {

        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
        helper('custom');
    }

    public function index() : string
    {

//        log_message('error' , date('Y.m.d H:i:s').' ] START CLI\index');
        echo date('Y.m.d H:i:s').' ] START CLI\index'. PHP_EOL;


//        log_message('error' , date('Y.m.d H:i:s').' ] END CLI\index');

        return date('Y.m.d H:i:s').' ] END CLI\index'. PHP_EOL;

    }
}