<?php
namespace App\Controllers;

use App\Libraries\CustomUploadsLib;
use App\Models\FileModel;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Psr\Log\LoggerInterface;

class Common extends BaseController
{
    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
    }

    public function index()
    {

    }

    public function upload_files($location)
    {

        $oUpload    = new CustomUploadsLib(); //업로드 관련 library

        if($this->request->getFile('upload')) //ckeditor
        {//텍스트 이미지 파일
            $aImg = $oUpload->run(['type' => $location , 'file_field' => 'upload']);
            if(!$aImg['success'])  $ret = ['error' => ['messgae' => '이미지[upload] 등록 중 문제가 발생했습니다.']];
            else $ret = ['url' => $aImg['data']['path']];
        }

        return $this->response->setJSON($ret);

    }

    //공지사항 첨부파일다운로드
    public function download_file(){

        $file_id = $this->request->getGetPost('file_id');

        if($file_id){
            $fileModel  = new FileModel();
            $oFileInfo  = $fileModel->find($file_id);
            $oFileInfo->download_counter = $oFileInfo->download_counter+1;
            $fileModel->save($oFileInfo); //다운로드 count update
            $aInput['org_file_name'] = $oFileInfo->o_f_name;
            $aInput['file_path'] = DOCROOT.$oFileInfo->f_path;
        }else{
            top_alert_script('필수입력사항 누락.');
            exit;
        }

        if(file_exists($aInput['file_path']) == false){
            top_alert_script('첨부파일이 없습니다.');
            exit;
        }


        return $this->response->download($aInput['file_path'], null)->setFileName($aInput['org_file_name']);

    }


}