<?php
namespace App\Controllers;

use App\Models\DashBoardModel;
use App\Models\PaymentModel;
use App\Models\QnaModel;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Psr\Log\LoggerInterface;

class DashBoard extends BaseController
{

    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {

        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
    }

    public function index()
    {

        $dashboard_model = new DashBoardModel();

        {//트래픽
            $aMrtgFilename = ['일간 트래픽', '주간트래픽', '월간트래픽', '년간트래픽'];
            $aMrtgFilepath = [
                'uploads/mrtg/61.74.195.215_eno1-day.png'
                , 'uploads/mrtg/61.74.195.215_eno1-week.png'
                , 'uploads/mrtg/61.74.195.215_eno1-month.png'
//                , 'uploads/mrtg/61.74.195.215_eno1-year.png'
            ];


            foreach ($aMrtgFilepath as $k => $v) {
                $filepath = WRITEPATH . $v;
                if (is_file($filepath)){
                    $aMrtgImg[$k]['data'] = getImgfileToData($filepath);
                    $aMrtgImg[$k]['last_modified'] = date("Y-m-d H:i:s", filemtime($filepath));
                    $aMrtgImg[$k]['traffic_name'] = $aMrtgFilename[$k];
                }
            }
        }

        {//매출통계

            $agent = $this->request->getUserAgent();
            $setPrevDay = 10;
            if($agent->isMobile()){
                $setPrevDay = 5;
            }

            $aTempData = $dashboard_model->getPaymentStatic('day');
            $aPaymentStatic_day = [];
            foreach ($aTempData as $r) {
                $aPaymentStatic_day[$r['pay_date']] = $r;
            }

            $aDate = [];
            for ($i = $setPrevDay; $i > -1 ; $i--) {
                $timestamp = strtotime("-{$i} days");
                $Ymd = date("Ymd", $timestamp);
                if(isset($aPaymentStatic_day[$Ymd])) $aDate[$Ymd] = $aPaymentStatic_day[$Ymd];
                else $aDate[$Ymd] = ['tot_amount' => 0 , 'pay_date_str' => view_date_format($Ymd,5) , 'pay_date' => $Ymd];
            }


//            zsView($aTempData);
        }

        {//1:1문의
            $qna_aInput = [
                    'del_yn' => 'N'
                ,   'isAnswer' => 'N'
            ];
            $qna_model = new QnaModel();
            $aQnaList = $qna_model->getQnaList($qna_aInput , false , 0 , 5);
        }

        {//취소요청

            $payment_aInput = [
                    'isReqCancel' => 'Y'
                ,   'search_text' => ''
            ];

            $payment_model = new PaymentModel();
            $aCanceOrderList = $payment_model->getPaymentList($payment_aInput,false,0,5);

        }

        $view_data = [
                'aMrtgImg'              => $aMrtgImg
            ,   'aPaymentStatic_day'    => $aDate
            ,   'aQnaList'              => $aQnaList
            ,   'aCanceOrderList'       => $aCanceOrderList
        ];

        $this->_header();
        echo view('dashboard/index' , $view_data);
        $this->_footer();

    }

}