<?php
namespace App\Controllers;

use App\Models\PaymentModel;
use App\Models\WehagoModel;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Psr\Log\LoggerInterface;

class Wehago extends BaseController
{

    public $pager;
    public $page        = 1; //페이지
    public $per_page    = 30; //페이지당 노출row

    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub

        $this->pager = \Config\Services::pager();

    }

    public function invoicePop()
    {

        $aInput = [ 'idx' => $this->request->getGet('id') ];

        $payment_model = new PaymentModel();
        $aInfo = $payment_model->asArray()->where(['idx' => $aInput['idx']])->first();
        $aInfo['supply_amount'] = getSupplyAmount($aInfo['amount']);//공급가액
        $aInfo['vat_amount'] = getVatAmount($aInfo['supply_amount']);//부가세액

        $wehago_model = new WehagoModel();
        $aWehagoInfo = $wehago_model->asArray()->where('nOrdIdx',$aInfo['order_id'])->first();

        if(empty($aWehagoInfo)){
            $enWehago = new \App\Entities\Wehago();
            $aWehagoInfo = $enWehago->getAttributes();
        }

        $aInfo = array_merge($aInfo, $aWehagoInfo);

        $view_data = [
            'aInfo' => $aInfo
        ];

        return view('wehago/invoice_pop', $view_data);
    }

    public function taxUpsert():ResponseInterface
    {

        $aInput         = $this->request->getPost();
        $wehago_model   = new WehagoModel();
        $enWehago       = new \App\Entities\Wehago();
        $isUpdate       = false;

        try{

            if($aInput['nIdx']){
                $isUpdate = true;
                $aInfo = $wehago_model->asArray()->where(['eTaxType' => 'P' , 'nIdx' => $aInput['nIdx']])->first();
                if($aInfo){
                    throw new \Exception('해당 주문건은 이미 세금계산서 발행이 완료되었습니다.');
                }
            }

            if(!$isUpdate) $aInput['dtRegDate'] = date('Y-m-d H:i:s');
            $aInput['vcAdminID'] = auth()->id();

            if(isset($aInput['wResults'])){
                $wResults = json_encode($aInput['wResults'] , JSON_UNESCAPED_UNICODE);
                unset($aInput['wResults']);
                $aInput['wResults'] = $wResults;
            }

            //set entity
            $enWehago->fill($aInput);
            //save
            $ret = $wehago_model->save($enWehago);

            if($ret){

                $idx    = $isUpdate ? $aInput['nIdx'] : $wehago_model->db->insertID();
                $aInfo  = $wehago_model->asArray()->find($idx);
                $aRet   = ['success' => true , 'msg' => '' , 'data' => $aInfo];

            }else{

                throw new \Exception('세금계산서 정보 저장 중 문제가 발생하였습니다.');

            }

        }catch (\Exception $e){
            $aRet   = ['success' => false , 'msg' => $e->getMessage() , 'data' => []];

        }

        return $this->response->setJSON($aRet);

    }

    public function wehago_login()
    {

        $aInput = [ 'id' => $this->request->getGet('id') ];

        $view_data = [
            'id' => $aInput['id']
        ];

        return view('wehago/wehago_login', $view_data);
    }


}