<?php
namespace App\Controllers;

use App\Models\CmcSyncModel;
use App\Models\UserModel;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Psr\Log\LoggerInterface;

class CmcSync extends BaseController
{

    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
    }

    public function index()
    {

        $encrypter          = \Config\Services::encrypter();

        if(auth()->loggedIn()){
            return redirect()->to('/')->with('error' , '로그아웃 후 다시 시도해주세요!');
        }

        $aInput = [
                'cmc_vcID'  => $this->request->getGet('id')
            //12개월 자동지급 secret code코드 : s%2BBL4CR5beuhwILfp0MGPdl4L6CZWyclHt9mUrQcb5P4Il5GGRW8qTYdYbLU%2FolDuxA%3D
            //24개월 자동지급 secret code코드 : EbIfHfRBLcbiVh1gLwowF7kF0on5EhlMF3qu0nsRzP9a39fV4curSLXkSiKXLc6wEHQ%3D
            ,   'scd'       => $this->request->getGet('scd')
        ];

        if($aInput['cmc_vcID'] == ''){
            return redirect()->to('/');
        }

        //connect cmcdb
        $cmc_db = db_connect('cmc');
        $model = new CmcSyncModel($cmc_db);
        $aInfo = $model->getCmcUserInfo($aInput['cmc_vcID']);

        if(empty($aInfo)){
            return redirect()->to('/')->with('error' , '잘못된 접근입니다.');
        }

        $aInfo['vcEmail'] = str_replace(' ' , '' , $aInfo['vcEmail']);

        $aInfo['s_use_date'] = '';
        $aInfo['e_use_date'] = '';
//        if( onlynumber((string)$aInfo['vcSmartEDate']) > date('Ymd')){ // 스마트기간으로 킨더캔버스 사용하도록 처리 :: 정책변경으로 사용안함
//            $aInfo['s_use_date'] = onlynumber((string)$aInfo['vcSmartSDate']);
//            $aInfo['e_use_date'] = onlynumber((string)$aInfo['vcSmartEDate']);
//        }

        $aInfo['scd'] = '';

        if(!empty($aInput['scd'])){

            $scd = $encrypter->decrypt(base64_decode($aInput['scd']));

            if(!in_array($scd , ['12' , '24'])){
                return redirect()->to('/')->with('error' , '잘못된 접근입니다.');
            }

            if($scd == '12'){ //12개월 자동 지급
                $aInfo['s_use_date'] = date('Ymd');
                $aInfo['e_use_date'] = date("Ymd", strtotime("+1 years"));
            }else{ //24개월 자동 지급
                $aInfo['s_use_date'] = date('Ymd');
                $aInfo['e_use_date'] = date("Ymd", strtotime("+2 years"));
            }

            $aInfo['scd'] = $scd;

        }

        $KAKAO_REQUEST_URL = '';
        if($aInfo['kakao'] == 'Y'){
            $KAKAO_REQUEST_URL = "https://kauth.kakao.com/oauth/authorize?client_id=".KAKAO_CLIENT_KEY."&redirect_uri=".urlencode(base_url().'Api/kakao').'&response_type=code&state='.$aInput['cmc_vcID'];
        }

        $user_model = new UserModel();
        $aUserInfo = $user_model->where('cmc_vcID' , $aInfo['vcID'])->first();

        if($aUserInfo){
            return redirect()->to('/')->with('error' , '이미 꼬망세에서 회원 이전을 완료하였습니다.');
        }


        $aUserInfo = $user_model->where('login_id' , $aInfo['vcID'])->first();

        $isID = false; //아이디 입력 필요여부
        $isEmail = false; //이메일 입력 필요여부

        if($aUserInfo){ //같은 로그인 아이디를 가진 사람이 있음
            $isID = true;
        }

        unset($aUserInfo);

        $aUserInfo = $user_model->where('user_email' , $aInfo['vcEmail'])->first();

        if($aUserInfo){ //같은 이메일를 가진 사람이 있음
            $isEmail = true;
        }

        $this->_header(true);
        echo view('auth/cmc_sync' , ['aInfo' => $aInfo , 'is' => ['email' => $isEmail , 'id' => $isID] , 'KAKAO_REQUEST_URL' => $KAKAO_REQUEST_URL]);
        $this->_footer(true);

    }


    public function upsert()
    {

        $aInput = [
                'cell_tel' => $this->request->getPost('vcMobile')
            ,   'email' => $this->request->getPost('vcEmail')
            ,   'username' => $this->request->getPost('vcName')
            ,   'zipcode' => $this->request->getPost('vcZip')
            ,   'address' => $this->request->getPost('vcAddress')
            ,   'address_detail' => $this->request->getPost('vcAddressDesc')
            ,   'cmc_vcID' => $this->request->getPost('vcID')
        ];

        $this->_header();
        echo view('auth/cmc_sync' , $aInput);
        $this->_footer();

    }

}