<?php
namespace App\Controllers;

use App\Models\CanvasModel_v2;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Psr\Log\LoggerInterface;

class Main extends BaseController
{
    public $page = 0;
    public $per_page = 30;

    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
    }

    public function index()
    {

        {//마지막 주 월요일을 구하기, 마지막주 월요일 이후에는 다음달 추천템플릿이 보이도록
            $lastday = date('t'); //이번달 마지막 날 day
            $lastDate = date('Ym').$lastday;//이번달 마지막날의 Ymd
            $calculate_count = date('w', strtotime($lastDate)) - 1;
            $last_monday = date("Ymd", strtotime("{$lastDate} - {$calculate_count} days")); //마지막 주 월요일

            if($calculate_count >= 0 && $last_monday <= date('Ymd')) $search_YM = date("Ym", strtotime("+1 months"));
            else $search_YM = date('Ym');
        }

        $canvas_model = new CanvasModel_v2();

        $aInput = [
                'show_YM'   => $search_YM
            ,   'view_type' => 'recommend'
            ,   'category'  => 'template'
        ];

        $aRecommend = $canvas_model->getTemplateGroupList($aInput);

        $aResult = [];
        $aResult2 = [];
        foreach ($aRecommend as $k => $r) {
            unset($aRecommend[$k]['blob_data']);

            if($r['seq'] > 7) $aResult[] = $r; //right
            else $aResult2[] = $r; //left
        }

        $encrypter      = \Config\Services::encrypter();
        $output = [
                'aList'     => $aResult
            ,   'aList2'    => $aResult2
            ,   'encrypter' => $encrypter
        ];
        $this->_header();
        echo view('main/index' , $output);
        $this->_footer();

    }
/**
 * @desc '월별 디자인'
    public function index()
    {
        $canvas_model   = new CanvasModel_v2();
        $curr_month = (int)date('m').'월';

        if(date('Ym') == '202407') $curr_month = '8월';

        $aMonthLists    = $canvas_model->getGroupList(['menu_type' => 'month']);

        $menu_type  = 'month';
        $first_data = $canvas_model->setTable('tb_group')->where(['menu_type'=>$menu_type , 'title' => $curr_month ])->orderBy('seq')->first();
        $aInput = [
                'group_id'  => $first_data['group_id']
            ,   'page'      => $this->request->getPost('page')
            ,   'menu_type' => $menu_type
        ];

        $set_page           = $this->request->getPostGet('page') ?? $this->page;
        $set_per_page       = $this->request->getPostGet('per_page') ?? $this->per_page;
        $s_limit            = max(($set_page - 1) * $set_per_page, 0);

        $canvas_model  = new CanvasModel_v2();
        $aList         = $canvas_model->getGroupList($aInput);

        foreach ($aList as $k => $r) {
            $aInput['group_id'] = $r['group_id'];
            $aGroupSubList = $canvas_model->getTemplateGroupList($aInput, false , $s_limit , $set_per_page);
            $aList[$k]['templates'] = $aGroupSubList;
        }

        $encrypter      = \Config\Services::encrypter();

        $aData = [
                'aList'         => $aList
            ,   'encrypter'     => $encrypter
            ,   'aMonthLists'   => $aMonthLists
            ,   'per_page'      => $this->per_page
            ,   'curr_month'    => $curr_month
        ];

        $this->_header_ctgr('month');
        echo view('main/index', $aData);
        $this->_footer();

    }
*/
}