<?php
namespace App\Controllers;

use App\Models\CanvasModel_v2;
use App\Models\TemplateModel;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Psr\Log\LoggerInterface;

class Search extends BaseController
{

    public $page = 0;
    public $per_page = 30;

    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
    }

    public function index()
    {

        $aInput = [
                'search_text' => $this->request->getGet('q')
            ,   'search_type' => $this->request->getGet('t')
        ];

        $template_model = new TemplateModel();
        $canvas_model = new CanvasModel_v2();
        if($aInput['search_type'] == ''){
            $aList =  $template_model->getTemplateList($aInput , false , 0 , $this->per_page);
        }else{
            $aList = $canvas_model->getTemplateGroupList($aInput , false , 0 , $this->per_page);

        }
        $encrypter      = \Config\Services::encrypter();

        $data = [
                'aList'     => $aList
            ,   'aInput'    => $aInput
            ,   'encrypter' => $encrypter
            ,   'per_page'  => $this->per_page
        ];

        $this->_header_ctgr( false , $aInput);
        echo view('search/index' , $data);
        $this->_footer();

    }

    public function getLists() : ResponseInterface
    {

        $aInput = [
                'page'          => $this->request->getPost('page')
            ,   'search_text'   => $this->request->getPost('search_text')
            ,   'search_type'   => $this->request->getPost('search_type')
        ];

        $set_page           = $aInput['page'] ?? $this->page;
        $set_per_page       = $this->request->getPostGet('per_page') ?? $this->per_page;
        $s_limit            = max(($set_page - 1) * $set_per_page, 0);

        $template_model = new TemplateModel();
        $canvas_model = new CanvasModel_v2();

        if($aInput['search_type'] == '') {
            $aList = $template_model->getTemplateList($aInput, false, $s_limit, $set_per_page);
        }else{
            $aList = $canvas_model->getTemplateGroupList($aInput , false , $s_limit , $this->per_page);
        }

        $encrypter      = \Config\Services::encrypter();
        foreach ($aList as $k => $r) {
            $strEnc = sprintf("%s_template__%s",date('YmdHis'),$r["template_id"]);
            $aList[$k]['sEnc'] = urlencode($encrypter->encrypt($strEnc));
        }

        $resp = [ 'success' => true , 'msg' => '' , 'data' => $aList ];

        return $this->response->setJSON($resp);

    }

}