<?php
namespace App\Controllers;

use App\Entities\Order;
use App\Entities\Paylog;
use App\Libraries\KCP;
use App\Libraries\SMS;
use App\Models\GoodsModel;
use App\Models\OrderModel;
use App\Models\PayLogModel;
use App\Models\UserModel;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Psr\Log\LoggerInterface;

class Test extends BaseController
{

    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub

        if(!isTest()){
            $this->show404();
        }

    }

    public function index()
    {

        $regx = '/\A[a-zA-Z0-9_\.]+\z/';

        $s[] = 'test';
        $s[] = 'test_test';

        foreach ($s as $v) {


            preg_match($regx , $v , $matches);
            zsView($matches);



        }





        $this->_header();
        echo view('test/index');
        $this->_footer();


    }

}